type ShopNote {
  name: String!
  items: [Item!] @relation
}

type Item {
  name: String!
  quantity: String!
  urgent: Boolean!
  checked: Boolean!
  note: ShopNote!
}

type Query {
  allShopNotes: [ShopNote!]!
}