mutation {
  createShopNote(data: {
    name: "Shopping List of Tapas"
    items: {
      create: [
        { name: "Laddo", checked: false, urgent: true, quantity: "2 packates of 500gm" }
        { name: "Milk", checked: false, urgent: false, quantity: "1 packate of 250gm" }
      ]
    }
  }) {
    _id
    name
    items {
      data {
        name,
		    checked,
        urgent,
        quantity
      }
    }
  }
}