mutation {
  createShopNote(data: {
    name: "Shopping List of Tapas"
    items: {
      create: [
        { name: "Laddo", checked: false, urgent: true }
        { name: "Milk", checked: false, urgent: false }
      ]
    }
  }) {
    _id
    name
    items {
      data {
        name,
		    checked,
        urgent
      }
    }
  }
}